FROM alpine:3.9 as alpine
RUN apk add -U --no-cache ca-certificates

FROM scratch

# Copy certificates
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD release/linux/amd64/dynamicdns-go /dynamicdns-go
ADD config.yaml /config.yaml

CMD ["/dynamicdns-go"]
